/*
    CRIE UMA CLASSE PARA REPRESENTAR CARROS.
    OS CARROS POSSUEM UMA MARCA, UMA COR E UM GASTO MÉDIO DE COMBUSTÍVEL(L/KM).
    CRIE UM MÉTODO QUE DADO A QUANTIDADE DE QUILÔMETROS E O PREÇO DO COMBUSTÍVEL
    NOS DÊ O VALOR GASTO EM REAIS PARA REALIZAR O PERCURSO.
*/